export const customersPageData = {
  title: "Lista de Clientes",
  description:
    "Confira abaixo a listagem completa com todos os clientes cadastrados em seu sistema, utilize esta seção para visualizar, consultar e gerenciar as informações de cada cliente de forma prática e organizada.",

  mock: {
    customers: [
      {
        id: 1,
        name: "Mariana Souza Almeida",
        cep: "22041001",
        address: "Rua Barata Ribeiro nº 245",
        neighborhood: "Copacabana",
        city: "Rio de Janeiro",
        uf: "RJ",
      },
      {
        id: 2,
        name: "Carlos Eduardo Mendes",
        cep: "30140071",
        address: "Avenida Afonso Pena nº 1200",
        neighborhood: "Centro",
        city: "Belo Horizonte",
        uf: "MG",
      },
      {
        id: 3,
        name: "Fernanda Ribeiro Costa",
        cep: "80010000",
        address: "Rua XV de Novembro nº 350",
        neighborhood: "Centro",
        city: "Curitiba",
        uf: "PR",
      },
      {
        id: 4,
        name: "Rodrigo Martins Pereira",
        cep: "01311000",
        address: "Avenida Paulista nº 1578",
        neighborhood: "Bela Vista",
        city: "São Paulo",
        uf: "SP",
      },
      {
        id: 5,
        name: "Juliana Ferreira Gomes",
        cep: "40020000",
        address: "Rua Chile nº 89",
        neighborhood: "Centro",
        city: "Salvador",
        uf: "BA",
      },
      {
        id: 6,
        name: "Lucas Henrique Batista",
        cep: "69005010",
        address: "Avenida Eduardo Ribeiro nº 540",
        neighborhood: "Centro",
        city: "Manaus",
        uf: "AM",
      },
      {
        id: 7,
        name: "Patrícia Nogueira Lima",
        cep: "70040900",
        address: "Esplanada dos Ministérios nº 1",
        neighborhood: "Zona Cívico-Administrativa",
        city: "Brasília",
        uf: "DF",
      },
      {
        id: 8,
        name: "Rafael Teixeira Barros",
        cep: "88010000",
        address: "Rua Felipe Schmidt nº 410",
        neighborhood: "Centro",
        city: "Florianópolis",
        uf: "SC",
      },
      {
        id: 9,
        name: "Camila Duarte Santana",
        cep: "50030000",
        address: "Rua do Bom Jesus nº 210",
        neighborhood: "Recife Antigo",
        city: "Recife",
        uf: "PE",
      },
      {
        id: 10,
        name: "Bruno Carvalho Lopes",
        cep: "64000040",
        address: "Avenida Frei Serafim nº 980",
        neighborhood: "Centro",
        city: "Teresina",
        uf: "PI",
      },
    ],
  },
};
